### ISSUE TITLE
How to run this project? i am new to gulp and it is showing error"Did you forget to signal async completion? " can you help me out

### ISSUE THREAD

**Issue by sthada** [jakezatecky/react-checkbox-tree#146]
**Describe the bug**
Please include a clear and concise description of what the bug is.

**Reproduction steps**
Please include the necessary steps to reproduce the issue as well as a live example that showcases it. You can modify this [CodeSandbox reference point](https://codesandbox.io/s/oj5wnyr7w9) to create a working example.

**Expected behavior**
Please include a clear and concise description of what you expected to happen.

**Screenshots**

**Comment by sthada** [comment]
Entrypoint main = index.browser.js
[12:50:33] Finished '<anonymous>' after 675 ms
[12:50:33] Finished 'build-script-web' after 14 s
[12:50:33] Starting 'compare-css-output'...
[12:50:33] Starting 'build-style'...
[12:50:33] Starting 'build-style-less'...
Fatal Error: Error code 1
Error: Command failed: scss-lint 'src/scss/react-checkbox-tree.scss' --format=JSON
'scss-lint' is not recognized as an internal or external command,
operable program or batch file.

    at C:\Users\shivamth\Desktop\Ejade-UI\react-checkbox-tree-master\node_modules\gulp-scss-lint\src\index.js:33:29
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at tryCatcher (C:\Users\shivamth\Desktop\Ejade-UI\react-checkbox-tree-master\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\shivamth\Desktop\Ejade-UI\react-checkbox-tree-master\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\shivamth\Desktop\Ejade-UI\react-checkbox-tree-master\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\shivamth\Desktop\Ejade-UI\react-checkbox-tree-master\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\shivamth\Desktop\Ejade-UI\react-checkbox-tree-master\node_modules\bluebird\js\release\promise.js:690:18)
    at _drainQueueStep (C:\Users\shivamth\Desktop\Ejade-UI\react-checkbox-tree-master\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\shivamth\Desktop\Ejade-UI\react-checkbox-tree-master\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\shivamth\Desktop\Ejade-UI\react-checkbox-tree-master\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\shivamth\Desktop\Ejade-UI\react-checkbox-tree-master\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
[12:50:33] The following tasks did not complete: default, build, compare-css-output, <parallel>, build-style, build-style-less
[12:50:33] Did you forget to signal async completion?

**Comment by jakezatecky** [comment]
Hey there. You are getting an error because `scsslint` is not installed. That is something used in the build process to validate the Sass files.

To run the project, you should install [Ruby](https://www.ruby-lang.org/en/downloads/). Then run the following:

``` shell
gem install sass scss_lint
```

After that, you might have to open a new console window and then run the build step again.

**Comment by jakezatecky** [comment]
I am closing out this issue. Please let me know if you still have problems,

To anyone else that might read this in the future, you can always find the guide for running the project in `examples/README.md`.

**Comment by Suvitruf** [comment]
Can we avoid using ruby? It's kinda strange to install ruby only to build scss,

**Comment by jakezatecky** [comment]
@Suvitruf Minor correction: it is only used for the linting tool (which also requires the Ruby flavor of Sass). I have been internally debating on migrating to an alternative linter or dropping linting altogether as none of the alternatives have even close to feature parity. I admit having to run an additional Ruby command is not ideal, but it is a one-time thing.
