### ISSUE TITLE
[TypeError: Cannot read property 'getRandomValues' of undefined in v1.1.0

### ISSUE THREAD

**Issue by aschonfeld** [jakezatecky/react-checkbox-tree#84]
I am trying to run a unit test on a component that uses react-checkbox-tree, but it fails in 1.1.0 with this error (works fine in 1.0.2):

```
Error: Uncaught [TypeError: Cannot read property 'getRandomValues' of undefined]
    at reportException (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at HTMLUnknownElementImpl._dispatch (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at HTMLUnknownElementImpl.dispatchEvent (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
    at HTMLUnknownElementImpl.dispatchEvent (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
    at HTMLUnknownElement.dispatchEvent (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
    at Object.invokeGuardedCallbackDev (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-dom/cjs/react-dom.development.js:138:16)
    at invokeGuardedCallback (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-dom/cjs/react-dom.development.js:187:29)
    at replayUnitOfWork (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-dom/cjs/react-dom.development.js:11318:7)
    at renderRoot (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-dom/cjs/react-dom.development.js:11885:11) TypeError: Cannot read property 'getRandomValues' of undefined
    at module.exports (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-checkbox-tree/lib/index.js:4698:17)
    at module.exports (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-checkbox-tree/lib/index.js:4683:15)
    at new CheckboxTree (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-checkbox-tree/lib/index.js:1360:50)
    at constructClassInstance (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-dom/cjs/react-dom.development.js:6801:20)
    at updateClassComponent (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-dom/cjs/react-dom.development.js:8336:9)
    at beginWork (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-dom/cjs/react-dom.development.js:8982:16)
    at performUnitOfWork (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-dom/cjs/react-dom.development.js:11814:16)
    at workLoop (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-dom/cjs/react-dom.development.js:11843:26)
    at HTMLUnknownElement.callCallback (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/react-dom/cjs/react-dom.development.js:100:14)
    at invokeEventListeners (/NImounts/NiNoSnapUsers/aschonfeld/dev/git/grail/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
The above error occurred in the <CheckboxTree> component:
    in CheckboxTree (created by ReactNodeTreePicker)
    in div (created by ReactNodeTreePicker)
    in ReactNodeTreePicker (created by Connect(ReactNodeTreePicker))
    in Connect(ReactNodeTreePicker)
    in Provider (created by WrapperComponent)
    in WrapperComponent
```

**Comment by jakezatecky** [comment]
Hmm... There is no invocation of `getRandomValues` in this library, so I unsure where this would come from. Did you happen to find the solution to this problem?

It could be that one of the functions being passed into the component makes a call to the titular `getRandomValues`, but that would be external to the component (although executed inside of it).

**Comment by effinrich** [comment]
@aschonfeld Did you find a solution to this?  I'm having the same problem.

thanks

**Comment by jakezatecky** [comment]
I recently I found out that the Crypto API is being used in one of my dependencies. The Crypto API has a  [`getRandomValues`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) method, so an undefined error likely means the global `crypto` is not available. This API is supported in all major browser versions and it appears to work in later versions of Node.

@aschonfeld @effinrich what Node versions are you using to run your tests?

**Comment by rmccallum** [comment]
Great plugin and works well in browser. Getting same crypto error when we run unit tests. Any update?

Node 8.9.4
Module Ver 1.2.3
Testing framework enzyme

**Comment by jakezatecky** [comment]
@rmccallum are you using `jsdom` or any tool to simulate some of the API accessible to the browser? If not, that is likely an issue. I may look into using an alternative library that does not rely on browser cryptographic functions that are seemingly absent in the base version of node.

**Comment by jakezatecky** [comment]
I have pushed a release candidate for v1.2.4 that includes a build that I think may resolve the issues experienced in this thread. It took quite a bit of detective work to determine the cause of this issue, and it mostly revolves around Webpack defaults and one of the dependencies not playing nicely with each other.

Please test with `react-checkbox-tree: 1.2.4-rc.0` to see if your errors goes away.

**Comment by effinrich** [comment]
@jakezatecky Worked for me!  Thanks very much.

**Comment by marisol88** [comment]
For me, the problem was the IE version. 
I had IE 10 compatibility in my html.
`<meta http-equiv="X-UA-Compatible" content="IE=10" />`

I had to change it:
`<meta http-equiv="X-UA-Compatible" content="IE=edge" />`
